### ISSUE TITLE
Declarative deployment

### ISSUE THREAD

**Issue by nazar-pc** [subspace/infra#123]
Currently we deploy things imperatively: running scripts that modify state such that it takes desired shape. This works, but it is problematic because we can't revert changes, can't ensure state is exactly what we expect it to be and use tools designed for infrastructure creation to do so.

What we want instead is declarative deployments:
* Likely some kind of template, in case of k8s it would be Helm chart with some variables
* Then instantiation of the template with variables filled in, environment variables and secrets configured in it
* When developer wants to instantiate something, they just send a pull request, when pull request is merged, something like Argo CD will apply necessary changes to make sure deployment matches what was defined in the repository exactly
* Destruction then is as simple as reverting a pull request

For this to work we need to pick a tool for declarative deployment, key storage solution and have some templates (ideally with readme) that the rest of the team can work with somewhat autonomously.
```[tasklist]
### Tasks
- [x] Add ArgoCD manager to kubernetes
- [x] setup argo cd in cluster
- [x] create helm charts for astral and nova
- [x] create kustomize manifests for networks
- [x] update helm charts for squids rewards, account, general
- [x] create argocd path for declarative deployments of resources
```

**Comment by DaMandal0rian** [comment]
#143 adds argocd manager to kubernetes cluster as an addon with terraform

**Comment by DaMandal0rian** [comment]
argocd now installed in cluster

![Image](https://github.com/subspace/infra/assets/3614052/a028a0ea-3ae1-4e63-ac35-ce4b82c1b94e)

**Comment by DaMandal0rian** [comment]
Added devnet k8s deployments:
- [x] https://github.com/subspace/infra/pull/307 
- [x] https://github.com/subspace/infra/pull/308
- [x] https://github.com/subspace/infra/pull/309

**Comment by DaMandal0rian** [comment]
Added squid deployments for k8s:

- [x] https://github.com/subspace/infra/pull/304
- [x] https://github.com/subspace/infra/pull/305
- [x] https://github.com/subspace/infra/pull/306

**Comment by DaMandal0rian** [comment]
Next agenda:
- Now i need to test these deployments in the cluster and connect it to argocd to manage the deployments when change is made to the path it tracks.
- Need to add secrets configs since sensitive info can't be used in configmaps, will look at how to have this injected from Vault. Likely solution i will use is https://github.com/kubernetes-sigs/secrets-store-csi-driver which gets the secrets from vault and mounts it as a CSI volume.
- Then i will add the secrets config to the statefulset manifests

**Comment by DaMandal0rian** [comment]
Latest fix for domain validation and argocd environments.
https://github.com/subspace/infra/pull/315/files
