### ISSUE TITLE
Grafana Loki monitoring and log collecting with Promtail/Grafana agent

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#144]
```[tasklist]
### Tasks
- [x] Configure Loki and Grafana Instance
- [x] Add Vector and Grafana agent to all servers
- [x] Add loki driver for docker and configure docker files with it
- [x] Update docker compose files in infra repo with driver for docker services
- [x] long term retention of logs
```
