### ISSUE TITLE
Write script to automate node key creation and syncing with vault KMS.

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#145]
```[tasklist]
### Tasks
- [x] currently encrypt keys in repo directly
- [x] create helm chart
- [x] deploy on kubernetes cluster (depends on #143)
- [ ] https://github.com/subspace/infra/issues/143
- [x] write script to automate key creation
- [x] write script to pull keys and populate on deployment
```

**Comment by DaMandal0rian** [comment]
This keys are currently encrypted for ephemeral devnet use which was pushed in the PR #226

**Comment by DaMandal0rian** [comment]
Script to automate node key creation is currently testing and will open PR shortly
