### ISSUE TITLE
cleanup Infra repo and update readme and docs

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#146]
```[tasklist]
### Tasks
- [x] remove old digitalocean terraform and network primitives
- [x] add readme for aws terraform and ephemeral runners
- [x] add ci/cd docs
- [x] explorer astral docs
- [x] add ansible readme docs
```

**Comment by DaMandal0rian** [comment]
opened #219

**Comment by DaMandal0rian** [comment]
opened https://github.com/subspace/infra/pull/241
