### ISSUE TITLE
Subspace Node Monitoring

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#147]
```[tasklist]
### Tasks
- [x] create dashboard
- [x] install cadvisor with grafana agent and push to grafana
- [x] expose prometheus on all nodes
- [x] push metrics to grafana with victoriametrics
```

**Comment by 0xjeremyfrank** [comment]
What exactly needs to be done for this?

**Comment by DaMandal0rian** [comment]
This will create a metrics monitoring specific for substrate based nodes once shamil exposes a metrics endpoint for prometheus. #144 is more specific to shipping logs and also general metrics for docker containers and system logs.
