### ISSUE TITLE
AWS ephemeral github runners

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#169]
```[tasklist]
### Tasks
- [x] create child module for runners ephemeral and linux
- [x] Integrate the Philipps official module to scale runners on AWS
- [x] Create Github App and webhook to connect with runner module
- [x] refactor unused resources
- [x] use spot market instances
- [x] create windows runner
- [x] testing
```

**Comment by DaMandal0rian** [comment]
This task is currently in draft PR https://github.com/subspace/infra/pull/230 

It will create ephemeral Linux runners for now with support for windows next.

Currently, the issue is getting the AWS serverless lambdas to communicate with the github app which I am debugging.

**Comment by DaMandal0rian** [comment]
I've made some progress on this; also added windows support. Iwill test the new changes tomorrow.
