### ISSUE TITLE
secure infrastructure

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#181]
```[tasklist]
### Tasks
- [x] Firewalls and Ports
- [x] malware detection tools
- [x] Auditing
- [x] Cloudflare
- [x] Trivy container scanning
- [x] rustsec and anchore
- [x] Gitguardina secrets detection in repos
```

**Comment by DaMandal0rian** [comment]
related CI scanning PR https://github.com/subspace/subspace/pull/2378
