### ISSUE TITLE
changes to devnet and gemini network terraform

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#182]
```[tasklist]
### Tasks
- [x] devnet changes
- [x] enable timekeeper on farmer node
- [x] add bootstrap domain evm node
- [x] gemini changes
- [x] remove datadog
- [x] add new relic
```
