### ISSUE TITLE
Github CI pipelines for automation of networks with terraform

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#184]
```[tasklist]
### Tasks
- [x] deploy gemini-3f with CI and terraform automation
- [x] deploy devnet with CI and terraform automation
- [x] deploy ephemeral devnets with CI and terraform automation
- [ ] https://github.com/subspace/infra/pull/183
```

**Comment by DaMandal0rian** [comment]
Currently in review #183
