### ISSUE TITLE
remove gemini-3f infra

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#212]
```[tasklist]
### Tasks
- [x] gemini-3f squids and archive
- [x] gemini-3f blockscout
- [x] remove status page endpoints
- [x] remove infra except 1 rpc and 1 boostrap node
- [x] remove logging and monitoring
```

**Comment by DaMandal0rian** [comment]
close #211  #213
