### ISSUE TITLE
Infra for gemini-3h

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#246]
```[tasklist]
### Tasks
- [ ] https://github.com/subspace/infra/pull/245
- [ ] https://github.com/subspace/infra/pull/243
- [ ] https://github.com/subspace/infra/pull/235
- [ ] https://github.com/subspace/infra/pull/247
```
