### ISSUE TITLE
macos runners hetzner

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#251]
```[tasklist]
### Tasks
- [x] configure macos runners
- [x] add to runner group on github org
- [x] test runners
- [x] change CI workflows to use new runners
- [ ] https://github.com/subspace/pulsar/pull/296
- [ ] https://github.com/subspace/subspace/pull/2505
```

**Comment by DaMandal0rian** [comment]
tested at https://github.com/subspace/pulsar/actions/runs/7781532838/job/21219218319

**Comment by DaMandal0rian** [comment]
PR for pulsar repo: https://github.com/subspace/pulsar/pull/296

**Comment by DaMandal0rian** [comment]
PR for monorepo:
https://github.com/subspace/subspace/pull/2505
