### ISSUE TITLE
Make hetzner terraform manifests for gemini and devnet

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#255]
Currently, we deploy networks with AWS on terraform, but we are migrating some infra to hetzner to balance/split the network, thus need automation to handle this.
```[tasklist]
### Tasks
- [x] create one module for hetzner
- [x] make child module for devnet and gemini networks
- [x] make ephemeral testing child module
```

**Comment by DaMandal0rian** [comment]
waiting on #263 to be reviewed and will start this
