### ISSUE TITLE
Setup general, accounts, and rewards squid in staging

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#297]
Create the micro squids in staging environment to test squid indexing for astral

```[tasklist]
### Tasks
- [x] setup general squid
- [x] setup rewards squid
- [x] setup account squid
```
