### ISSUE TITLE
extend infra to support Auto domain

### ISSUE THREAD

**Issue by DaMandal0rian** [subspace/infra#313]
Extend the terraform in infra to support another domain, in this case "Auto".
```[tasklist]
### Tasks
- [ ] https://github.com/subspace/infra/pull/311
- [ ] https://github.com/subspace/infra/pull/312
- [ ] https://github.com/subspace/infra/pull/314
```

**Comment by DaMandal0rian** [comment]
I've opened 2 PRs both for our main infra and testing framework @vedhavyas
