### ISSUE TITLE
Migrate All Infra to Infra Repo

### ISSUE THREAD

**Issue by 0xjeremyfrank** [subspace/infra#91]
This includes:

```[tasklist]
### Tasks
- [ ] #88
- [x] https://github.com/subspace/infra/issues/139
- [ ] https://github.com/subspace/infra/issues/90
- [x] https://github.com/subspace/infra/issues/136
- [x] https://github.com/subspace/infra/issues/137
```

**Comment by DaMandal0rian** [comment]
closing as this is complete
